# Generated by Django 3.2.5 on 2021-07-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='cate')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(default='mecanicos/no_hay_imagen.jpg', upload_to='mecanicos')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='--')),
                ('usuario', models.CharField(default='--', max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webRayoMakween.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webRayoMakween.mecanico')),
            ],
        ),
    ]
